{% set version = "21.1.1" %}

package:
  name: xorg-xserver
  version: {{ version }}

source:
  url: https://github.com/freedesktop/xorg-xserver/archive/refs/tags/xorg-server-{{ version }}.tar.gz
  sha256: 915edd49f394283cc587b88a68b5e13e6e2d7f0276edabc9249afb2e22adf634

requirements:
  build:
    - meson
    - ninja
    - compilers
    - autoconf
    - automake
    - cmake
    - pkg-config
    - bison
    - libxkbfile
    - xorg-xtrans
    - pixman
    - xorg-libx11
    - libdrm
    - epoxy
    - libtool
    - freetype
    - xorg-font-util
#    - xorg-xorgproto
    - xorg-xproto
    - xorg-util-macros
    - xorg-libx11
    - xorg-fontsproto
    - xorg-randrproto
    - xkeyboard-config
    
  host:
    - libxkbfile
    - xorg-xtrans
    - pixman
    - xorg-libx11
    - libdrm
    - epoxy
    - libtool
    - freetype
    - xorg-font-util
#    - xorg-xorgproto
    - xorg-xproto
    - xorg-util-macros
    - xorg-libx11
    - xorg-fontsproto
    - xkeyboard-config

